version: '2'
services:
  database:
    volumes:
      - /home/vbelkevich/git/micreservices-homework/database:/opt/h2-data
    ports:
      - "81:81"
    image: oscarfonts/h2
    expose:
      - "1521"
  school-class:
    build: .
    ports:
      - "8082:10000"
    depends_on:
      - database
